"""add activities

Revision ID: e7c2727841bd
Revises: ddf9b7174d00
Create Date: 2026-03-15 23:37:13.657696

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c2727841bd"
down_revision: str | Sequence[str] | None = "ddf9b7174d00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["activities.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_activities_parent_id", "activities", ["parent_id"], unique=False)
    op.create_index(
        "uq_activities_parent_lower_name",
        "activities",
        [sa.literal_column("coalesce(parent_id, 0)"), sa.literal_column("lower(name)")],
        unique=True,
    )
    op.create_table(
        "organization_activities",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("organization_id", "activity_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_activities")
    op.drop_index("uq_activities_parent_lower_name", table_name="activities")
    op.drop_index("ix_activities_parent_id", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
